# Site settings
title: Grin


# Build settings
baseurl: /GrinSite # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: "noticias.html"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "index"
    values:
      layout: "index"

# Custom variables
version: "1.1.0"





# Options
custom_header: false
custom_nav_footer: false
reverse: false

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap